# Generated by Django 5.1.1 on 2024-09-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imutness_rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
